# Generated by Django 4.2.7 on 2023-11-21 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='email_adress',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
