# Generated by Django 4.2.7 on 2023-11-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_rename_email_users_email_adress_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
