# Generated by Django 4.2.7 on 2023-12-02 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=45, null=True),
        ),
    ]
