# Generated by Django 4.2.7 on 2023-12-02 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_shows_app', '0002_alter_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(max_length=45),
        ),
    ]
