# Generated by Django 4.2.7 on 2023-12-02 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_shows_app', '0003_alter_show_description_alter_show_release_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='show',
            old_name='title',
            new_name='Title',
        ),
    ]
