# Generated by Django 4.2.7 on 2023-12-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tv_shows_app', '0004_rename_title_show_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='Title',
            field=models.CharField(max_length=40),
        ),
    ]
